### ISSUE TITLE
QQ回调不成功

### ISSUE THREAD

**Issue by Bobobbb** [wangyansnow/WYShareSDK#1]
else if ([resp isKindOfClass:[QQBaseResp class]]) { // QQ分享

```
    QQBaseResp *qqresp = (QQBaseResp *)resp;
    NSLog(@"%@",qqresp.result);
    if (_finished) {
        WYShareResponse *response = [WYShareResponse shareResponseWithSucess:(qqresp.type == 0) errorStr:qqresp.errorDescription];
        _finished(response);
    }
}
```

}

将
(qqresp.type == 0)
改成：
([qqresp.result intValue] == 0)

不然分享信息成功时，不能收到一个成功的回调信息，不管成功与否qqresp.type都是0，而[qqresp.result intValue]成功是0，失败是-4

**Comment by wangyansnow** [comment]
恩,我查看了,确实存在这个问题,我更新一下,谢谢提出解决这个问题的方法
